/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atividadecaluladora;


import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class AtividadeCalculadora2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AtividadeCalculadora2.class.getName());

    /**
     * Creates new form AtividadeCalculadora2
     */
    public AtividadeCalculadora2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setType(java.awt.Window.Type.POPUP);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setText("8");
        jButton1.addActionListener(this::clicouBotao);

        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setText("7");
        jButton2.addActionListener(this::clicouBotao);

        jButton3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton3.setText("9");
        jButton3.addActionListener(this::clicouBotao);

        jButton4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton4.setText("(");
        jButton4.addActionListener(this::clicouBotao);

        jButton5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton5.setText(")");
        jButton5.addActionListener(this::clicouBotao);

        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setText("log");
        jButton6.addActionListener(this::clicouBotao);

        jButton8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton8.setText("4");
        jButton8.addActionListener(this::clicouBotao);

        jButton10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton10.setText("5");
        jButton10.addActionListener(this::clicouBotao);

        jButton11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton11.setText("6");
        jButton11.addActionListener(this::clicouBotao);

        jButton12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton12.setText("+");
        jButton12.addActionListener(this::clicouBotao);

        jButton13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton13.setText("-");
        jButton13.addActionListener(this::clicouBotao);

        jButton14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton14.setText("sin");
        jButton14.addActionListener(this::clicouBotao);

        jButton17.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton17.setText("1");
        jButton17.addActionListener(this::clicouBotao);

        jButton18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton18.setText("2");
        jButton18.addActionListener(this::clicouBotao);

        jButton19.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton19.setText("3");
        jButton19.addActionListener(this::clicouBotao);

        jButton20.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton20.setText("*");
        jButton20.addActionListener(this::clicouBotao);

        jButton21.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton21.setText("^");
        jButton21.addActionListener(this::clicouBotao);

        jButton22.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton22.setText("cos");
        jButton22.addActionListener(this::clicouBotao);

        jButton25.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton25.setText("C");
        jButton25.addActionListener(this::clicouBotao);

        jButton26.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton26.setText("0");
        jButton26.addActionListener(this::clicouBotao);

        jButton27.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton27.setText("=");
        jButton27.addActionListener(this::clicouBotao);

        jButton28.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton28.setText("÷");
        jButton28.addActionListener(this::clicouBotao);

        jButton29.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jButton29.setText("/");
        jButton29.addActionListener(this::clicouBotao);

        jButton30.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton30.setText("tan");
        jButton30.addActionListener(this::clicouBotao);

        jButton7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton7.setText(".");
        jButton7.addActionListener(this::clicouBotao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton22)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    boolean resultadoMostrado = false;  
    
    // pega o botao clicado
    private void clicouBotao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicouBotao
        JButton pegaBotao = (JButton)evt.getSource(); 
        String botao = pegaBotao.getText(); 
        
        if (botao.equals("=")) {
            try {               
                String exprecao = areaTexto.getText(); 
                List<String> posfixa = infixaParaPosfixa(exprecao); 
                double resultado = calcularPosfixa(posfixa); 
                areaTexto.setText(String.valueOf(resultado)); 
                resultadoMostrado = true;
                
            } catch (Exception ex) {
                areaTexto.setText("ERRO"); 
                resultadoMostrado = true;
            }
        }
        
        else if (botao.equals("C")) { areaTexto.setText(""); } 
        
        else { 
            if (botao.matches("\\d") || botao.equals(".")) { 
                if (resultadoMostrado) {
                    areaTexto.setText(botao);
                    resultadoMostrado = false;
                    
                } else { 
                    areaTexto.setText(areaTexto.getText() + botao); 
                    
                }
                
            } else {                 
                if (resultadoMostrado && precedencia(botao) == 4 || botao.equals("(")) { 
                    areaTexto.setText(botao + " " + areaTexto.getText());                                     
                    resultadoMostrado = false;
                    
                }else {          
                    areaTexto.setText(areaTexto.getText() + " " + botao + " ");
                    resultadoMostrado = false;
                }          
            }
        }
    }//GEN-LAST:event_clicouBotao
    
    // prioridade
    static int precedencia(String op) {
        switch (op) {
            case "+": case "-": return 1;
            case "*": case "/": return 2;
            case "^": return 3;
            case "log": case "sin": case "cos": case "tan": case "sqrt": return 4;
        }
        return 0;
    }
    
    // todos os operadores
    static boolean operadores(String s) {
        return s.matches("[+\\-*/^]")
            || s.equals("log")
            || s.equals("sin")
            || s.equals("cos")
            || s.equals("tan")
            || s.equals("sqrt");
    }
    
    // empilha a conta em posfixa
    static List<String> infixaParaPosfixa(String exprecao) {
        Stack<String> ops = new Stack<>();
        List<String> saida = new ArrayList<>();

        String[] tokens = exprecao.split(" ");
        
        for (String t : tokens) {
            if (t.matches("\\d+(\\.\\d+)?")) { 
                saida.add(t);
            } 
            else if (operadores(t)) { 
                while (!ops.isEmpty() && precedencia(ops.peek()) >= precedencia(t)) {
                    saida.add(ops.pop());
                }
                ops.push(t);
            } 
            else if (t.equals("(")) {
                ops.push(t);
            } 
            else if (t.equals(")")) {
                while (!ops.peek().equals("(")) {
                    saida.add(ops.pop());
                }
                ops.pop();
            }
        }

        while (!ops.isEmpty()) {
            saida.add(ops.pop());
        }

        return saida;
    }
    
    // faz a conta
    static double calcularPosfixa(List<String> posfixa) {
        Stack<Double> pilha = new Stack<>();

        for (String t : posfixa) {
            if (t.matches("\\d+(\\.\\d+)?")) {
                pilha.push(Double.parseDouble(t));
            } 
            else {
                if (t.equals("log")) {
                    double a = pilha.pop();
                    pilha.push(Math.log10(a));
                }
                else if (t.equals("sin")) {
                    pilha.push(Math.sin(Math.toRadians(pilha.pop())));
                } 
                else if (t.equals("cos")) {
                    pilha.push(Math.cos(Math.toRadians(pilha.pop())));
                } 
                else if (t.equals("tan")) {
                    pilha.push(Math.tan(Math.toRadians(pilha.pop())));
                } 
                else if (t.equals("sqrt")) {
                    pilha.push(Math.sqrt(pilha.pop()));
                } 
                else {
                    double b = pilha.pop();
                    double a = pilha.pop();

                    switch (t) {
                        case "+": pilha.push(a + b); break;
                        case "-": pilha.push(a - b); break;
                        case "*": pilha.push(a * b); break;
                        case "/": pilha.push(a / b); break;
                        case "^": pilha.push(Math.pow(a, b)); break;
                    }
                }
            }
        }

        return pilha.pop();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and areaTexto the form */
        java.awt.EventQueue.invokeLater(() -> new AtividadeCalculadora2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
